services:
  SurveysPortal-DB:
    image: postgres
    restart: always
    container_name: SurveysPortal-DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SurveysPortalDB
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  SurveysPortal-API:
    image:  surveys-portal:latest
    restart: unless-stopped
    tty: true
    container_name: SurveysPortal-API
    build:
     context: .
     dockerfile: src/Backend/Dockerfile
    ports:
    - "4040:4040"
    depends_on:
      SurveysPortal-DB:
        condition: service_healthy
    environment:
      - POSTGRES__CONNECTIONSTRING=Host=SurveysPortal-DB;Database=SurveysPortalDB;Username=postgres;Password=postgres

  SurveysPortal-WEB:
    restart: unless-stopped
    image: surveys-portal:latest
    container_name: SurveysPortal-WEB
    build:
      context: .
      dockerfile: src/Frontend/SurveysPortalWeb/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      SurveysPortal-API:
        condition: service_healthy