services:
  SurveysPortal-DB:
    image: postgres
    restart: always
    container_name: SurveysPortal-DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SurveysPortalDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  SurveysPortal-API:
    container_name: SurveysPortal-API
    image:  surveys-portal:latest
    restart: unless-stopped
    tty: true
    depends_on:
      SurveysPortal-DB:
        condition: service_healthy
    build:
     context: .
     dockerfile: src/Backend/Dockerfile
    ports:
    - "4040:4040"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:4040/health || exit 1" ]
      start_period: 30s
      interval: 5s
    environment:
      - POSTGRES__CONNECTIONSTRING=Host=SurveysPortal-DB;Database=SurveysPortalDB;Username=postgres;Password=postgres

  SurveysPortal-WEB:
    container_name: SurveysPortal-WEB
    image: surveys-portal:latest
    restart: unless-stopped
    tty: true
    depends_on:
      SurveysPortal-API:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Frontend/SurveysPortalWeb/Dockerfile
    ports:
      - "4200:4200"