@SurveysPortal.Modules.Surveys.QuestionAnswer.Api_HostAddress = http://localhost:5273

GET {{SurveysPortal.Modules.Surveys.QuestionAnswer.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
