version: '3.7'

services:
  SurveysPortal-db:
    image: postgres
    container_name: SurveysPortal-DB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SurveysPortalDB
    ports:
      - 5433:5432
    networks:
      - SurveysPortal-network

  SurveysPortal-api:
    image: postgres
    ports:
      - 5154:80
    depends_on:
      - test-db
    environment:
      - CONNECTIONSTRINGS__DEFAULT=User ID=postgres;Password=postgres;Host=test-db;Port=5433;Database=postgres
    networks:
      - SurveysPortal-network

networks:
  test-network:
    driver: bridge
