name: Merge any release branch to uat
on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge develop -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: master
          github_token: ${{ secrets.TESTOWANIETOKENA }}
