name: Merge to master any changes in develop branch
on:
  push:
    branches:
      - 'feature/*'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge develop -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: feature/*
          target_branch: develop
          github_token: ${{ secrets.TESTOWANIETOKENA }}